### ISSUE TITLE
oauth credentials

### ISSUE THREAD

**Issue by ghost** [dhruvrajan/presidential-candidate-analysis#1]
The consumer_key, consumer_secret, access_token, access_secret should not be public.
Anyone that has this information has access to the associated twitter account.
You may want to remove the existing strings from project.py , unauthorize the application, and generate new oauth credentials.
I have not used the software nor accessed the twitter account, just notifying you of the possible issue.

**Comment by dhruvrajan** [comment]
Thanks for alerting me to this issue, @lnxdork. I've regenerated the oauth credentials, and removed them from the code repository. Should be fixed now. Thanks again!
